### ISSUE TITLE
How can I run the baseline model on GPU? 

### ISSUE THREAD

**Issue by ldong1111** [sigmorphon/2021-task1#14]
I found out that the code for the baseline model is implemented by dyNet. I ran it directly and found that the code only runs on the CPU and not on the GPU. However, I found that dyNet is built to support GPU, but I can't find any GPU parameters in the source code. So how can I run the baseline model on GPU?

**Comment by kylebgorman** [comment]
You will have to reconfigure how dyNet is built (the dyNet our requirements.txt installs is not set up for GPU support) as well as pass some environmental variables. I spent many hours on it and don't even exactly recall what I did. As it happens though, this is a rare case where the code doesn't go any faster when you run it on GPU.

Since this repo really just exists for the shared task I don't intend to support that here. However, somebody (not me) should fork this code and rewrite in PyTorch and then experiment with GPU support there.

**Comment by ldong1111** [comment]
> You will have to reconfigure how dyNet is built (the dyNet our requirements.txt installs is not set up for GPU support) as well as pass some environmental variables. I spent many hours on it and don't even exactly recall what I did. As it happens though, this is a rare case where the code doesn't go any faster when you run it on GPU.
> 
> Since this repo really just exists for the shared task I don't intend to support that here. However, somebody (not me) should fork this code and rewrite in PyTorch and then experiment with GPU support there.

Thank you for your reply. This is not a big problem, because the source code can be run directly and it's not very slow.
