### ISSUE TITLE
Double transcription in English entry

### ISSUE THREAD

**Issue by tresoldi** [sigmorphon/2021-task1#4]
The transcription for "nehru" in the English training file has two entries, separated by a comma: (https://github.com/sigmorphon/2021-task1/blob/c27ad79c919300d9f7959360f425e537cff84d6e/data/high/eng_us_train.tsv#L20519)

The issue is caused by the Wiktionary transcription:  /ˈneɪru, ˈnɛru/ (https://en.wiktionary.org/wiki/Nehru)

**Comment by kylebgorman** [comment]
We'll fix this too, thanks for report. We recently added some code to check for this case but the English data was extracted before this hit WikiPron. 

I'd probably just promote the /n e ɪ r u/ pronunciation (since it's listed first and the other seems prescriptively wrong to me as an US Eng. speaker).
